### ISSUE TITLE
Missing recent feed entries

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/planet.ros.org#15]
(Rewriting my post) I found that some recent posts don't show up on planet.ros.org. Examples I manually found, which their feeds look fine on other RSS viewer (e.g. http://codebeautify.org/rssviewer):

- Robbie Upgrade http://escaliente-robotics.blogspot.com/2015/06/robbie-upgrade.html
- rss test purpose only (for debugging planet.ros.org not pulling some feeds issue) http://ros-logger.blogspot.com/2015/07/rss-test-purpose-only.html

Actually, browsing all the available posts as of today from the oldest post (May 28, 2015) up to today (Jul 21, 2015), only posts from ROS news, ROS Industrial, MoveIt!, PAL Robotics blog can be seen on planet.ros.org.

Taking my blogspot.com blog as an example:

- I specified RSS2.0 instead of ATOM1.0 in https://github.com/ros-infrastructure/planet.ros.org/pull/14 but seems not working yet.
- It was not updated for years until recently. I noticed that there's an [inactive threashold](https://github.com/ros-infrastructure/planet.ros.org/blob/50900cb762156738f45327e7576ff5a61dc9d9d7/ros.ini#L20) in ros.ini, but haven't figured how it works (maybe around [this portion of code](https://github.com/rubys/venus/blob/70810fff6a8f43c81892369c53294eb77fc79ad6/planet/spider.py#L250)).

**Comment by 130s** [comment]
(Rewriting my post) I found that some recent posts don't show up on planet.ros.org. Examples I manually found:

- Robbie Upgrade http://escaliente-robotics.blogspot.com/2015/06/robbie-upgrade.html
- rss test purpose only (for debugging planet.ros.org not pulling some feeds issue) http://ros-logger.blogspot.com/2015/07/rss-test-purpose-only.html

Actually, browsing all the available posts as of today from the oldest post (May 28, 2015) up to today (Jul 21, 2015), only posts from ROS news, ROS Industrial, MoveIt!, PAL Robotics blog can be seen on planet.ros.org.

Taking my blogspot.com blog as an example:

- I specified RSS2.0 instead of ATOM1.0 in https://github.com/ros-infrastructure/planet.ros.org/pull/14 but seems not working yet.
- It was not updated for years until recently. I noticed that there's an [inactive threashold](https://github.com/ros-infrastructure/planet.ros.org/blob/50900cb762156738f45327e7576ff5a61dc9d9d7/ros.ini#L20) in ros.ini, but haven't figured how it works (maybe around [this portion of code](https://github.com/rubys/venus/blob/70810fff6a8f43c81892369c53294eb77fc79ad6/planet/spider.py#L250)).

**Comment by 130s** [comment]
Asked a related question on Venus repo https://github.com/rubys/venus/issues/34

**Comment by tfoote** [comment]
Does it have a label "ROS" I notice your test post is not tagged with ROS: http://ros-logger.blogspot.com/search/label/ROS which will get filtered out. I don't see a tag cloud to filter the Robbie Update so don't know if it has the tag to be selected.

**Comment by 130s** [comment]
Sorry! Labelling does the trick (I noticed it's documented in the instruction). 
I [poked](http://escaliente-robotics.blogspot.com/2015/06/robbie-upgrade.html?showComment=1438229811400#c1419115890701738418) the author of Robbie blog.
