### ISSUE TITLE
index page is shown at http://planet.ros.org/

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/planet.ros.org#18]
![scr_planet ros org_indexseen](https://cloud.githubusercontent.com/assets/1840401/14301300/8c99905c-fb4b-11e5-9279-a00e9e415504.png)

Same from FF 45 and Chrome 49 on Ubuntu 14.04.

**Comment by tfoote** [comment]
OSUOSL broke the apache config this afternoon. The rolled it back half an hour later. @wjwwood @gerkey  This was the same outage as the ros wiki. It's resolved now.
