### ISSUE TITLE
Posts from moveit.ros.org not appearing

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/planet.ros.org#23]
Latest post is Jan 4, 2017 that doesn't seem to be pulled in to planet.

- Feed is [registred](https://github.com/ros-infrastructure/planet.ros.org/blob/bed0ccc7a301ee9f3a157390ee1017ed913dc7ad/ros.ini#L126) and the URL seems to be functional. 
- Category `ROS` is [set](https://github.com/ros-planning/moveit.ros.org/pull/115/files#diff-1bc26ac35068fcb4e55993a40905540aR11) in the blog post IMO (although I'm not yet sure if `categories` section works for RSS tag purpose).

If there is a way to look at server log and see any hint from there that'll be great.

**Comment by tfoote** [comment]
Looking here: view-source:http://moveit.ros.org/feed I don't see any category tags. Like I do say here: https://ros-logger.blogspot.com/feeds/posts/default?alt=rss

**Comment by 130s** [comment]
Thank you. I need to look more into, but,

- I actually don't find category tags in the successful example (even saved the feed and opened it in an editor).
- Using online RSS reader (e.g. http://feedreader.com) the last post pulled from moveit.ros.org is Jul 2015. So something is wrong in the RSS feed.
