### ISSUE TITLE
http://bluesat.com.au/tag/ros/feed/

### ISSUE THREAD

**Issue by hjed** [ros-infrastructure/planet.ros.org#24]
Would you be able to add the ros section of our blog? http://bluesat.com.au/tag/ros/feed/ (if you need to the unfiltered feed its http://bluesat.com.au/feed/)

Also I don't know if its possible but could you add rel="canonical" to your title links, as google expects that from content aggregators when linking to original articles.

**Comment by tfoote** [comment]
Please submit a PR to add your blog to the config. 

WRT canonical links. We don't have subpages for each element which means that canonical links cannot be used as the content is in the body: https://webmasters.stackexchange.com/questions/75788/can-rel-canonical-links-be-included-in-rss-feeds and https://webmasters.googleblog.com/2013/04/5-common-mistakes-with-relcanonical.html give more explainations.

**Comment by tfoote** [comment]
It looks like there's an RSS feed native "source" tag that could be used and is proposed upstream: https://github.com/rubys/venus/pull/20 that would be similar to the canonical reference. 

I'm going to close this as there's no action items for the repository. We request PRs for adding feeds so there's easy git history to browse for submissions.

**Comment by hjed** [comment]
Ok, fair enough. Never mind about the canonical thing. I've submitted a pull request.
