### ISSUE TITLE
Feed http://bluesat.com.au/feed/ timed out

### ISSUE THREAD

**Issue by ramereth** [ros-infrastructure/planet.ros.org#30]
I'm getting the following error every hour for the cronjob:
```
WARNING:planet.runner:Timeout in thread-0
WARNING:planet.runner:Feed http://bluesat.com.au/feed/ timed out
```

**Comment by tfoote** [comment]
Loading it in my browser I get the feed loading in 2.9 seconds. Which is slow but not horrible.  @ramereth do you know what the timeouts are set to?

![image](https://user-images.githubusercontent.com/447804/51573053-9957bf80-1e5c-11e9-9f1e-e731cbc85acc.png)

@hjed is this response time expected? You added this entry in #26  And are you expecting to be posting more ROS content in the future?
