### ISSUE TITLE
Put planet.ros.org on status.ros.org?

### ISSUE THREAD

**Issue by mgruhler** [ros-infrastructure/planet.ros.org#37]
Motivated by a recent [question on ROS answers](https://answers.ros.org/question/342685/is-planetrosorg-down/), I was wondering if it wouldn't make sense to put `planet.ros.org` also on `status.ros.org`.

(Posting here, as I couldn't find a repo or anything for `status.ros.org`).

Thanks for your consideration.

**Comment by tfoote** [comment]
Thanks for the suggestion. I added it to the status page: https://status.ros.org/

**Comment by mgruhler** [comment]
Cool, thanks for the quick response!
